version: "3.9"

services:
  backend-camera:
    image: putthakun01/backend-camera:latest  
    container_name: backend-camera
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - RABBITMQ_HOST=SY_rabbitmq
    devices:
      - "/dev/video0:/dev/video0"
    privileged: true
    ports:
      - "8888:5000"
    restart: always
    networks:
      - SY_network

networks:
  SY_network:
    external: true
